version: "3.7"
services:
  app:
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
    command: sh /scripts/command.sh
    stdin_open: true
    tty: true
  db:
    image: postgres
    ports:
      - "5432:5432"
